#
# Copyright © 2016-2023 The Thingsboard Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

availabilityZones: [ eu-west-1a,eu-west-1b,eu-west-1c ]

metadata:
  name: thingsboard-mqtt-broker-cluster
  region: eu-west-1
  version: "1.23"

managedNodeGroups:
  - name: tb-mqtt-broker
    instanceType: m6g.metal
    desiredCapacity: 0
    maxSize: 25
    minSize: 0
    labels: { role: tb-mqtt-broker }
    volumeType: gp3
    volumeSize: 10
    ssh:
      allow: true
      publicKeyName: 'dlandiak'
    preBootstrapCommands:
      - echo 'Starting custom preBootstrapCommands'
      - echo 'fs.nr_open = 16777216' | sudo tee -a /etc/sysctl.conf
      - echo 'fs.file-max = 16777216' | sudo tee -a /etc/sysctl.conf
      - echo Reloading sysctl
      - sudo sysctl -p
      - echo Setting limits
      - echo '*                soft    nofile          16777216' | sudo tee -a /etc/security/limits.conf
      - echo '*                hard    nofile          16777216' | sudo tee -a /etc/security/limits.conf
      - echo 'root             soft    nofile          16777216' | sudo tee -a /etc/security/limits.conf
      - echo 'root             hard    nofile          16777216' | sudo tee -a /etc/security/limits.conf
      - echo '*                soft    nproc          16777216' | sudo tee -a /etc/security/limits.conf
      - echo '*                hard    nproc          16777216' | sudo tee -a /etc/security/limits.conf
      - echo 'root             soft    nproc          16777216' | sudo tee -a /etc/security/limits.conf
      - echo 'root             hard    nproc          16777216' | sudo tee -a /etc/security/limits.conf
      - sudo sysctl -p
      - echo 'Patching Docker /etc/docker/daemon.json for Kubernetes 1.23 on dockerd'
      - cp /etc/docker/daemon.json /tmp/docker-original.json
      - echo '{"default-ulimits":{"nofile":{"Name":"nofile","Soft":16777216,"Hard":16777216}}}' > /tmp/docker-patch.json
      - jq -s '.[0] * .[1]' /tmp/docker-original.json /tmp/docker-patch.json | sudo tee /etc/docker/daemon.json
      - echo 'Restarting Docker'
      - sudo systemctl daemon-reload
      - sudo systemctl restart docker.service
  - name: tb-perf-test-publishers
    instanceType: c6g.12xlarge
    desiredCapacity: 0
    maxSize: 1
    minSize: 0
    volumeType: gp3
    volumeSize: 10
    labels: { role: tb-perf-test-publishers }
    ssh:
      allow: true
      publicKeyName: 'dlandiak'
  - name: tb-perf-test-subscribers
    instanceType: c6g.8xlarge
    desiredCapacity: 0
    maxSize: 1
    minSize: 0
    volumeType: gp3
    volumeSize: 10
    labels: { role: tb-perf-test-subscribers }
    ssh:
      allow: true
      publicKeyName: 'dlandiak'
  - name: tb-additional
    instanceType: m6a.large
    desiredCapacity: 0
    maxSize: 1
    minSize: 0
    volumeType: gp3
    volumeSize: 10
    labels: { role: tb-additional }
    ssh:
      allow: true
      publicKeyName: 'dlandiak'
  - name: tb-kafka
    instanceType: m6a.2xlarge
    desiredCapacity: 0
    maxSize: 9
    minSize: 0
    volumeType: gp3
    volumeSize: 10
    labels: { role: tb-kafka }
    ssh:
      allow: true
      publicKeyName: 'dlandiak'

# In order to scale the node groups from 1 (desiredCapacity: 1) to X execute the following commands:
# eksctl scale nodegroup --cluster=thingsboard-mqtt-broker-cluster --nodes=X tb-mqtt-broker
# eksctl scale nodegroup --cluster=thingsboard-mqtt-broker-cluster --nodes=X tb-kafka